### ISSUE TITLE
project_type/name shouldn't be hardcoded

### ISSUE THREAD

**Issue by swbsf** [bibliosansfrontieres/ideascube-deploy#12]
https://github.com/bibliosansfrontieres/ideascube-deploy/blob/master/roles/update_device_config/tasks/main.yml#L40

This is too fragile. Best bet is we don't deal with IDB and KB with this repo.

**Comment by letompouce** [comment]
I agree about the test being damn fragile. Since the `project_name` is derived from users input, and users being users, we can bet there will be a project name matching `/kb|idb|idc/` sooner or later :-)

At least the regexp should read `regex_search('(^idb)'`.
