### ISSUE TITLE
reset.sh: logs should be removed

### ISSUE THREAD

**Issue by swbsf** [bibliosansfrontieres/ideascube-deploy#19]
So we don't get confused with previous installations. I would say at least:
```
/var/log/nginx/*
/var/log/apt/history*
/var/log/apt/term*
/var/log/ansible-pull.log
/var/log/tinc.testvpn.log
```

**Comment by letompouce** [comment]
Moved to https://gitlab.com/bibliosansfrontieres/olip-bsf/cap/factory-config/-/issues/3
